apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Chart.Replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      volumes:
        - name: app-config
          configMap:
            name: environment.properties
            items:
            - key: environment.properties
              path: application.properties
      containers:
        - name: app
          image: {{ .Values.registry }}/cdp-app:{{ .Chart.Version }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: app-config
              mountPath: /home/demo/application.properties
              subPath: application.properties
